assessments/urls.py
from django.urls import path
from . import views

app_name = "assessments"

urlpatterns = [
    path('assessment/<int:assessment_id>/', views.StudentAssessmentView.as_view(), name='student_assessment'),
    path('assessment_list/', views.StudentAssessmentListView.as_view(), name='student_assessment_list'),
    path('assessment_creation/', views.CreateAssessmentView.as_view(), name='assessment_creation'),
    
    path('course/<int:course_id>/assessments/', views.CourseAssessmentsView.as_view(), name='student_course_assessment_list'),

    path('professor_assessments/', views.ProfessorAssessmentListView.as_view(), name='professor_assessment_list'),
]

"""
    path('professor/courses/', views.ProfessorFeedbackCoursesView.as_view(), name='professor_courses'),
    path('professor/courses/<int:course_id>/assessments/', views.ProfessorAssessmentsView.as_view(), name='professor_assessments'),
    path('professor/courses/<int:course_id>/assessments/<int:assessment_id>/teams/', views.ProfessorFeedbackTeamsView.as_view(), name='professor_teams'),
    path('professor/courses/<int:course_id>/assessments/<int:assessment_id>/teams/<int:team_id>/feedback/', views.ProfessorIndividualFeedbackView.as_view(), name='professor_team_feedback'),
    path('student/courses/', views.StudentCoursesView.as_view(), name='student_courses'),
    path('student/courses/<int:course_id>/assessments/', views.StudentAssessmentsView.as_view(), name='student_assessments'),
"""

landing/urls.py
from django.urls import path
from . import views
from assessments.views import ProfessorFeedbackCoursesView, StudentCourseListView, ProfessorFeedbackAssessmentsView, ProfessorFeedbackTeamsView, ProfessorIndividualFeedbackView, StudentAssessmentView, StudentFeedbackView, ProfessorFeedbackFinalView

app_name = "landing"

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('team_creation/', views.CreateTeamView.as_view(), name='team_creation'),
    path('course_creation/', views.CreateCourseView.as_view(), name='course_creation'),
    path('courses/', views.CourseListView.as_view(), name='course_list'),

    path('professor/feedback/', ProfessorFeedbackCoursesView.as_view(), name='professor_feedback_courses'),
    path('professor/feedback/<int:course_id>/', ProfessorFeedbackAssessmentsView.as_view(), name='professor_feedback_assessments'),
    path('professor/feedback/<int:course_id>/<int:assessment_id>/', ProfessorFeedbackTeamsView.as_view(), name='professor_feedback_teams'),
    path('professor/feedback/<int:course_id>/<int:assessment_id>/<int:team_id>/', ProfessorIndividualFeedbackView.as_view(), name='professor_feedback_individual'),
    path('professor/feedback/<int:course_id>/<int:assessment_id>/<int:team_id>/<str:member_id>/', ProfessorFeedbackFinalView.as_view(), name='professor_feedback_final'),
    #in 'professor_feedback_individual' we still need to create a link from a person's name to the corresponding feedback 
    # - currently any team is shown to have no members 
    # - and every user's team and course field contains everyone's courses and teams, not just the individual user's
    # the url can be something like 'professor/feedback/<int:course_id>/<int:assessment_id>/<int:team_id>/individual_feedback

    #also still have to fix the student feedback flow
    path('student/courses/', StudentCourseListView.as_view(), name='student_courses'),
    path('student/courses/<int:course_id>/assessments/', StudentAssessmentView.as_view(), name='student_assessments'),
    path('student/courses/<int:course_id>/assessments/<int:assessment_id>/feedback/', StudentFeedbackView.as_view(), name='student_feedback'),
]

oauth/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "oauth"

urlpatterns = [
    path('auth/', views.AuthView.as_view(), name="auth"),
    path('callback/', views.CallbackView.as_view(), name="callback"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('registration/', views.RegistrationView.as_view(), name="registration"),
    path('registration_callback/', views.RegistrationCallbackView.as_view(), name="registration_callback"),
]

peervue/urls.py
"""
URL configuration for peervue

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
"""

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('', include('assessments.urls')),
    path('oauth/', include("oauth.urls"))
]

templates/base.html
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
      <title>PeerVue</title>
    {% endblock %}
  
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  
    {% block base_style %}
      {% load static %}
      <link rel="stylesheet" href="{% static 'css/base.css' %}">
      <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    {% endblock base_style %}
    {% block head_content %}{% endblock %}
  </head>
  <body>
    {% block navbar %}
      <div class="navbar">
        <a href="{% url 'landing:dashboard' %}" class="nav-logo">
          <div class="peer-vue">PeerVue</div>
        </a>
        
        <div class="nav-links">
          
          <a href="{% url 'landing:course_list' %}" class="nav-btn">
            <div class="nav-text">Courses</div>
          </a>
          
          
          <a href="{% url 'assessments:student_assessment_list' %}" class="nav-btn">
            <div class="nav-text">Assessments</div>
          </a>
          {% if user_role == 'admin' %}
            <a href="{% url 'landing:professor_feedback_courses' %}" class="nav-btn">
              <div class="nav-text">Feedback</div>
            </a>
          {% else %}
            <a href="{% url 'landing:student_courses' %}" class="nav-btn">
              <div class="nav-text">Feedback</div>
            </a>
          {% endif %}
        </div>
      </div>
    {% endblock %}
    {% block content %}{% endblock %}
  </body>
</html>